# docker-compose.yml
version: '2'

services:
    db:
        image: mysql
        ports:
            - 3306:3306
        volumes:
            - "./mysql/var/lib/mysql:/var/lib/mysql"
            - "/opt/www/money-pp.dmytrienko.tld/db/moneypp:/var/lib/mysql/moneypp"
        environment:
            MYSQL_ROOT_PASSWORD: root
    redis:
        image: redis:alpine
        ports:
            - 6379:6379
    php:
        build: php7-fpm
        ports:
            - 9000:9000
        links:
            - db:mysqldb
            - redis
        volumes:
            - /opt/www/money-pp.dmytrienko.tld/site:/var/www/symfony/money-pp.dmytrienko.tld
    nginx:
        build: nginx
        ports:
            - 80:80
        links:
            - php
        volumes_from:
            - php
        volumes:
            - ./nginx/var/log/nginx:/var/log/nginx
    elk:
        image: willdurand/elk
        ports:
            - 81:80
        volumes:
            - ./elk/logstash:/etc/logstash
            - ./elk/logstash/patterns:/opt/logstash/patterns
        volumes_from:
            - php
            - nginx

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8080:80"
        links:
            - db


